# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-12 09:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Models', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyBook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('price', models.IntegerField()),
                ('type', models.CharField(max_length=10)),
                ('authorer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Models.Author')),
            ],
        ),
    ]
