# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-12 14:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Models', '0003_books'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mybook',
            name='authorer',
        ),
        migrations.AddField(
            model_name='book',
            name='author',
            field=models.ManyToManyField(to='Models.Author'),
        ),
    ]
