# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-12 14:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Models', '0004_auto_20171112_1403'),
    ]

    operations = [
        migrations.CreateModel(
            name='Xbook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('namew', models.CharField(max_length=20)),
                ('price', models.IntegerField()),
                ('type', models.CharField(max_length=10)),
                ('author', models.ManyToManyField(to='Models.Author')),
            ],
        ),
    ]
