# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-19 03:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Models', '0006_auto_20171112_1510'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('alias', models.CharField(max_length=50)),
                ('type', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=10)),
                ('length', models.FloatField()),
                ('director', models.CharField(max_length=30)),
            ],
        ),
    ]
